### ISSUE TITLE
System.NullReferenceException when adding a plugin in Sample Host

### ISSUE THREAD

**Issue by fgoulet** [obiwanjacobi/vst.net#31]
I tried 3 different VST plugins in the Sample Host and I got this exception when I click the add button

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Jacobi.Vst.Host.Interop
  StackTrace:
   at Jacobi.Vst.Host.Interop.VstUnmanagedPluginContext.Initialize(String pluginPath)
   at Jacobi.Vst.Host.Interop.VstPluginContext.Create(String pluginPath, IVstHostCommandStub hostCmdStub)
   at Jacobi.Vst.Samples.Host.MainForm.OpenPlugin(String pluginPath) in C:\Users\frede\source\repos\vst.net\Source\Samples\Jacobi.Vst.Samples.Host\MainForm.cs:line 43

  This exception was originally thrown at this call stack:
    [External Code]
    Jacobi.Vst.Samples.Host.MainForm.OpenPlugin(string) in MainForm.cs

**Comment by obiwanjacobi** [comment]
Thanks for reporting this. I fixed the source code. Will be a while before a new (nuget) release...
Otherwise ping me on the VST.NET Discord server and I'll send you the binaries.

**Comment by fgoulet** [comment]
Cool, I should be able to build it so I don’t think I will need the binaries.
Thanks a lot!

**Comment by obiwanjacobi** [comment]
Ok. Have fun!
